### ISSUE TITLE
Adding metadata to the benchmarking output

### ISSUE THREAD

**Issue by julianpalladino** [UDST/manta#16]
Per @waddell 's request, we should add to the benchmarking output:
- The number of trips simulated.
- Total cumulative run time.
- Run time per trip.
- Maximum number of threads being used in each step.

Also, to assure that there's no overhead in between the components we should measure and output the total simulation time.

**Comment by waddell** [comment]
@juli Can you also add the maximum number of threads being used in each step?

**Comment by julianpalladino** [comment]
Sure!
